FROM llmbreakguard-base:latest

ARG JAVA_VERSION=17
ARG MAVEN_VERSION=3.9.6
ARG OLD_VERSION
ARG NEW_VERSION
ARG LIBRARY_GROUP_ID
ARG LIBRARY_NAME

RUN bash -c "source /root/.sdkman/bin/sdkman-init.sh \
    && JAVA_ID=\$(sdk list java | grep -E '${JAVA_VERSION}\.[0-9].*-tem' | head -1 | awk '{print \$NF}') \
    && echo \"Installing Java: \$JAVA_ID\" \
    && sdk install java \$JAVA_ID \
    && sdk default java \$JAVA_ID"

RUN bash -c "source /root/.sdkman/bin/sdkman-init.sh \
    && sdk install maven ${MAVEN_VERSION} \
    && sdk default maven ${MAVEN_VERSION}"

COPY . /project
WORKDIR /project

RUN bash -c "source /root/.sdkman/bin/sdkman-init.sh \
    && mvn versions:use-dep-version \
        -Dincludes='${LIBRARY_GROUP_ID}:${LIBRARY_NAME}' \
        -DdepVersion='${NEW_VERSION}' \
        -DforceVersion=true \
        -Dpmd.skip=true \
        -Dcheckstyle.skip=true \
        -Denforcer.skip=true \
        -q \
    || sed -i \
        's|<version>${OLD_VERSION}<\/version>|<version>${NEW_VERSION}<\/version>|g' \
        /project/pom.xml"

RUN bash -c "source /root/.sdkman/bin/sdkman-init.sh \
    && mvn compile \
        -Dpmd.skip=true \
        -Dcheckstyle.skip=true \
        -Denforcer.skip=true \
        -q \
    && echo 'passed' > /project/compile_status.txt \
    || echo 'failed' > /project/compile_status.txt"

RUN bash -c "source /root/.sdkman/bin/sdkman-init.sh \
    && mvn dependency:build-classpath \
        -DincludeScope=test \
        -Dmdep.outputFile=/project/test-classpath.txt \
        -q"