"""
prompt_llm.py

PURPOSE:
    Reads prompt files generated by generate_prompt.py and calls the
    Anthropic API to generate test classes. Writes raw LLM output to
    the staged directory alongside the prompt files.

DESIGN DECISIONS:
    1. READS FROM MANIFEST NOT FILE SYSTEM SCAN
       - Iterates manifest rows/classes/usage_blocks to find prompt files
         rather than scanning directories.
       - Reason: manifest is the single source of truth for what needs to
                 be generated. Scanning directories could pick up stale
                 files from previous runs.

    2. RESUME CAPABILITY VIA PROGRESS FILE
       - Tracks last successfully processed test class name in progress.json.
       - Reason: LLM generation is the most expensive and time-consuming step.
                 If it fails midway (rate limit, credits, network), resuming
                 from the last successful call avoids re-generating and
                 re-paying for already completed calls.

    3. SKIP EXISTING OUTPUT FILES
       - If a staged test file already exists it is skipped.
       - Reason: same as above, avoid redundant API calls on resume.

    4. TEMPERATURE=0 FOR DETERMINISTIC OUTPUT
       - All API calls use temperature=0.
       - Reason: deterministic generation makes results reproducible across
                 runs, important for a research and testing tool.

    5. STREAMING API CALLS
       - Uses Anthropic streaming API instead of blocking calls.
       - Reason: test generation with full class source in prompt can exceed
                 the default request timeout. Streaming keeps the connection
                 alive for long responses.

    6. REQUEST DELAY BETWEEN CALLS
       - 2 second delay between consecutive API calls.
       - Reason: avoids hitting per-minute rate limits on Anthropic API,
                 especially when processing many usage blocks in one run.

    7. RAW LLM OUTPUT SAVED AS-IS
       - The raw response from the LLM is saved without any post-processing.
       - Reason: post-processing (stripping markdown fences, fixing package
                 declarations) is handled by transplant_tests.py so that
                 the original LLM output is always preserved for debugging.

    8. API KEY FROM ENVIRONMENT VARIABLE
       - LLM_API_KEY is read from environment, injected by action.yml.
       - Reason: secrets must never be in config files or hardcoded.
                 GitHub Actions injects them as environment variables.
"""

import os
import sys
import json
import time
import anthropic
from datetime import datetime
from pathlib import Path

REQUEST_DELAY    = 2.0
MAX_OUTPUT_TOKENS = 32768
MODEL_NAME       = os.environ.get("LLM_MODEL", "claude-sonnet-4-6")


class Logger:
    """
    Tees stdout to both terminal and a log file.
    Keeps a full record of the LLM generation run for debugging.
    """
    def __init__(self, logfile_path):
        self.terminal = sys.stdout
        self.log      = open(logfile_path, "a", encoding="utf-8")

    def write(self, message):
        self.terminal.write(message)
        self.log.write(message)

    def flush(self):
        self.terminal.flush()
        self.log.flush()


def init_client():
    api_key = os.environ.get("LLM_API_KEY")
    if not api_key:
        print("LLM_API_KEY environment variable is not set")
        sys.exit(1)
    return anthropic.Anthropic(api_key=api_key)


def save_progress(progress_file, test_class_name):
    data = {
        "last_test_class": test_class_name,
        "timestamp":       datetime.now().isoformat()
    }
    with open(progress_file, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


def load_progress(progress_file):
    if Path(progress_file).exists():
        with open(progress_file) as f:
            return json.load(f)
    return None


def call_llm(client, prompt, max_retries=3):
    """
    Calls Anthropic API with retry logic for transient errors and
    rate limits. Returns (response_text, should_exit).
    should_exit is True only for unrecoverable errors like auth
    failure or exhausted credits.
    """
    for attempt in range(max_retries):
        try:
            response_text = ""
            with client.messages.stream(
                model=MODEL_NAME,
                max_tokens=MAX_OUTPUT_TOKENS,
                temperature=0,
                messages=[{"role": "user", "content": prompt}]
            ) as stream:
                for text in stream.text_stream:
                    response_text += text
            return response_text, False

        except anthropic.RateLimitError as e:
            retry_after = None
            if hasattr(e, "response") and e.response is not None:
                retry_after = e.response.headers.get("retry-after")
            wait_time = int(retry_after) + 5 if retry_after else 65
            print(f"rate limit hit, waiting {wait_time}s before retry")
            time.sleep(wait_time)
            continue

        except anthropic.APIStatusError as e:
            if e.status_code == 402:
                print("anthropic account has insufficient credits")
                print("add credits at https://console.anthropic.com/settings/billing")
                print("progress has been saved, re-run to resume")
                return None, True

            elif e.status_code == 401:
                print("anthropic authentication error, check LLM_API_KEY")
                return None, True

            elif e.status_code in (500, 502, 503, 529):
                if attempt < max_retries - 1:
                    wait_time = (2 ** attempt) * 5
                    print(f"server error {e.status_code}, retrying in {wait_time}s")
                    time.sleep(wait_time)
                    continue
                return f"error after {max_retries} retries: {e}", False

            else:
                return f"api error: {e}", False

        except anthropic.APIConnectionError as e:
            if attempt < max_retries - 1:
                wait_time = (2 ** attempt) * 5
                print(f"connection error, retrying in {wait_time}s")
                time.sleep(wait_time)
                continue
            return f"connection error after {max_retries} retries: {e}", False

        except Exception as e:
            return f"unexpected error: {e}", False

    return "error: max retries exceeded", False


def process_all_prompts(manifest_path):
    with open(manifest_path) as f:
        manifest = json.load(f)

    # set up logging to file alongside manifest
    log_dir  = Path(manifest_path).parent
    log_file = log_dir / "llm_generation_log.txt"
    progress_file = log_dir / "llm_progress.json"

    sys.stdout = Logger(log_file)

    llm_client = init_client()

    progress    = load_progress(progress_file)
    should_skip = progress is not None

    if progress:
        print(f"resuming from previous run")
        print(f"last processed: {progress['last_test_class']}")
        print(f"timestamp: {progress['timestamp']}")

    total   = sum(
        len(c["usage_blocks"])
        for r in manifest["rows"]
        for c in r["classes"]
    )
    done    = 0
    written = 0
    skipped = 0
    errors  = 0

    print(f"\nstarting LLM generation")
    print(f"model     : {MODEL_NAME}")
    print(f"total     : {total} prompt(s)")
    print(f"started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    for row_entry in manifest["rows"]:
        row_num = row_entry["row_index"]

        for class_entry in row_entry["classes"]:

            for usage_block in class_entry["usage_blocks"]:
                test_class_name = usage_block["test_class_name"]
                staged_path     = Path(usage_block["staged_path"])
                prompt_path     = staged_path.parent / f"{test_class_name}_prompt.txt"

                done += 1

                # resume: skip until we pass the last processed entry
                if should_skip:
                    if test_class_name == progress["last_test_class"]:
                        should_skip = False
                        print(f"found resume point at {test_class_name}, continuing from next")
                    else:
                        print(f"skipping {test_class_name} (already processed)")
                        skipped += 1
                    continue

                # skip if output already exists
                if staged_path.exists():
                    print(f"[{done}/{total}] skipping {test_class_name} (output exists)")
                    skipped += 1
                    continue

                if not prompt_path.exists():
                    print(f"[{done}/{total}] prompt file not found: {prompt_path}")
                    errors += 1
                    continue

                with open(prompt_path, encoding="utf-8") as f:
                    prompt = f.read()

                print(f"[{done}/{total}] row {row_num} | {test_class_name}")

                response, should_exit = call_llm(llm_client, prompt)

                if should_exit:
                    print(f"\nstopped at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
                    print(f"written: {written}, skipped: {skipped}, errors: {errors}")
                    sys.exit(1)

                if response and not response.startswith("error"):
                    staged_path.parent.mkdir(parents=True, exist_ok=True)
                    with open(staged_path, "w", encoding="utf-8") as f:
                        f.write(response)
                    print(f"  saved: {staged_path}")
                    written += 1
                    save_progress(progress_file, test_class_name)
                else:
                    print(f"  failed: {response}")
                    errors += 1

                if done < total:
                    time.sleep(REQUEST_DELAY)

    print(f"\nLLM generation complete")
    print(f"finished at : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"total       : {total}")
    print(f"written     : {written}")
    print(f"skipped     : {skipped}")
    print(f"errors      : {errors}")
    print(f"log         : {log_file}")


if __name__ == "__main__":
    manifest_path = sys.argv[1]   # /tmp/llmbreakguard/manifest.json
    process_all_prompts(manifest_path)